# ================================
# CREATE DATABASE OF WALMART SALES
# ================================
CREATE DATABASE MUSIC_STORE_PROJECT;


# ===============================
# USE WALMART_SALES_DATA DATABASE
# ===============================
USE MUSIC_STORE_PROJECT;


# ======================================================
# 1. WHO IS THE SENIOR MOST EMPLOYEE BASED ON JOB TITLE?
# ======================================================
SELECT *
FROM
	EMPLOYEE
ORDER BY
	LEVELS
    DESC LIMIT 1;


# ==========================================
# 2. WHICH COUNTRIES HAVE THE MOST INVOICES?
# ==========================================
SELECT
	COUNT(INVOICE_ID) AS INVOICE,
    BILLING_COUNTRY AS BILLING_COUNTRY
FROM INVOICE
GROUP BY
	BILLING_COUNTRY
ORDER BY
	BILLING_COUNTRY
    DESC;
    
    
# ===============================================
# 3. WHAT ARE THE TOP 3 VALUES OF TOTAL INVOICES?
# ===============================================
SELECT *
FROM
	INVOICE
ORDER BY
	TOTAL
    DESC LIMIT 3;
    

# =========================================================================================================================================
# 4. WHICH CITY HAS THE BEST CUSTOMERS? WE WOULD LIKE TO THROW A PROMOTIONAL MUSIC FESTIVAL IN THE CITY WE MADE THE MOST MONEY.
#	 WRITE A QUERY THAT RETURNS ONE CITY THAT HAS THE HIGHEST SUM OF INVOICE TOTALS. RETURN BOTH THE CITY NAME & SUM OF ALL INVOICE TOTALS.
# =========================================================================================================================================
SELECT
	BILLING_CITY,
    SUM(TOTAL) AS TOTAL
FROM INVOICE
GROUP BY
	BILLING_CITY
ORDER BY
	TOTAL
    DESC LIMIT 1;
    
    
# =================================================================================================
# 5. WHO IS THE BEST CUSTOMER? THE CUSTOMER WHO HAS SPENT THE MOST MONEY WILL BE THE BEST CUSTOMER.
#	 WRITE A QUERY THAT RETURNS THE PERSON WHO HAS SPENT THE MOST MONEY.
# =================================================================================================
SELECT
    CUSTOMER.CUSTOMER_ID,
    CUSTOMER.FIRST_NAME,
    CUSTOMER.LAST_NAME,
    SUM(INVOICE.TOTAL) AS TOTAL
FROM CUSTOMER
JOIN INVOICE
ON CUSTOMER.CUSTOMER_ID = INVOICE.CUSTOMER_ID
GROUP BY
    CUSTOMER.CUSTOMER_ID,
    CUSTOMER.FIRST_NAME,
    CUSTOMER.LAST_NAME
ORDER BY
    TOTAL DESC
LIMIT 1;


# =================================================================================================
# 6. WRITE A QUERY TO RETURN THE EMAIL, FIRST NAME, LAST NAME, & GENRE OF ALL ROCK MUSIC LISTENERS.
#	 RETURN YOUR LIST ORDERED ALPHABETICALLY BY EMAIL STARTING WITH A.
# =================================================================================================
SELECT DISTINCT
	EMAIL,
    FIRST_NAME,
    LAST_NAME
FROM CUSTOMER
JOIN INVOICE
ON CUSTOMER.CUSTOMER_ID = INVOICE.CUSTOMER_ID
JOIN INVOICE_LINE
ON INVOICE.INVOICE_ID = INVOICE_LINE.INVOICE_ID
WHERE
	TRACK_ID
    IN (SELECT TRACK_ID
		FROM TRACK
		JOIN GENRE
		ON GENRE.GENRE_ID = TRACK.GENRE_ID
		WHERE GENRE.NAME
		LIKE 'ROCK')
ORDER BY
	EMAIL;
    

# ============================================================================================
# 7. LET'S INVITE THE ARTISTS WHO HAVE WRITTEN THE MOST ROCK MUSIC IN OUR DATASET.
# 	 WRITE A QUERY THAT RETURNS THE ARTIS NAME AND TOTAL TRACK COUNT OF THE TOP 10 ROCK BANDS.
# ============================================================================================
SELECT
	ARTIST.ARTIST_ID,
    ARTIST.NAME,
    COUNT(TRACK.TRACK_ID) AS NUM_OF_SONGS
FROM ARTIST
JOIN ALBUM
ON ALBUM.ARTIST_ID = ARTIST.ARTIST_ID
JOIN TRACK
ON TRACK.ALBUM_ID = ALBUM.ALBUM_ID
WHERE GENRE_ID
	IN (SELECT GENRE_ID
    FROM GENRE
    WHERE NAME
    LIKE "ROCK")
GROUP BY
	ARTIST.ARTIST_ID,
    ARTIST.NAME
ORDER BY
	NUM_OF_SONGS
    DESC LIMIT 10;
    

# =================================================================================================================    
# 8. RETURN ALL THE TRACK NAMES THAT HAVE A SONG LENGTH LONGET THAN THE AVERAGE SONG LENGTH.
#	 RETURN THE NAME AND MILLISECONDS FOR EACH TRACK. ORDER BY THE SONG LENGTH WITH THE LONGEST SONGS LISTED FIRST.
# =================================================================================================================
SELECT
	NAME,
    MILLISECONDS
FROM TRACK
WHERE
	MILLISECONDS > (SELECT AVG(MILLISECONDS) AS AVG_TRACK_LENGTH
					 FROM TRACK)
ORDER BY
	MILLISECONDS
    DESC;
    
    
# ==================================================================================================================================
# 9. FIND HOW MUCH AMOUNT SPENT BY EACH CUSTOMER ON ARTISTS. WRITE A QUERY TO RETURN THE CUSTOMER NAME, ARTIST NAME, AND TOTAL SPENT
# ==================================================================================================================================
WITH BEST_SELLING_ARTIST AS
	(SELECT ARTIST.ARTIST_ID AS ARTIST_ID,
		ARTIST.NAME AS ARTIST_NAME,
        SUM(INVOICE_LINE.UNIT_PRICE * INVOICE_LINE.QUANTITY) AS TOTAL_SPENT
	FROM INVOICE_LINE
    JOIN TRACK
    ON TRACK.TRACK_ID = INVOICE_LINE.TRACK_ID
    JOIN ALBUM
    ON ALBUM.ALBUM_ID = TRACK.ALBUM_ID
    JOIN ARTIST
    ON ARTIST.ARTIST_ID = ALBUM.ARTIST_ID
    GROUP BY
		ARTIST.ARTIST_ID, ARTIST.NAME
    ORDER BY 
		TOTAL_SPENT
		DESC LIMIT 1)
SELECT
	CUSTOMER.CUSTOMER_ID AS CUSTOMER_ID,
    CUSTOMER.FIRST_NAME AS NAME,
    BEST_SELLING_ARTIST.ARTIST_NAME AS ARTIST_NAME,
    SUM(INVOICE_LINE.UNIT_PRICE * INVOICE_LINE.QUANTITY) AS TOTAL_SPENT
FROM INVOICE
JOIN CUSTOMER
ON CUSTOMER.CUSTOMER_ID = INVOICE.CUSTOMER_ID
JOIN INVOICE_LINE
ON INVOICE_LINE.INVOICE_ID = INVOICE.INVOICE_ID
JOIN TRACK
ON TRACK.TRACK_ID = INVOICE_LINE.TRACK_ID
JOIN ALBUM
ON ALBUM.ALBUM_ID = TRACK.ALBUM_ID
JOIN BEST_SELLING_ARTIST
ON BEST_SELLING_ARTIST.ARTIST_ID = ALBUM.ARTIST_ID
GROUP BY
	CUSTOMER.CUSTOMER_ID,
    CUSTOMER.FIRST_NAME,
    BEST_SELLING_ARTIST.ARTIST_NAME
ORDER BY
	TOTAL_SPENT
    DESC;
    
    
# ======================================================================================================================================================
# 10. WE WANT TO FIND OUT THE MOST POPULAR MUSIC GENRE FOR EACH COUNTRY.
#	  WE DETERMINE THE MOST POPULAR GENRE AS THE GENRE WITH THE HIGHEST AMOUNT OF PURCHASES.
#	  WRITE A QUERY THAT RETURNS EACH COUNTRY ALONG WITH THE TOP GENRE. FOR COUNTRIES WHERE THE MAXIMUM NUMBER OF PURCHASES IS SHARED RETURN ALL GENRES.
# ======================================================================================================================================================
WITH POPULAR_GENRE AS
	(SELECT
		COUNT(INVOICE_LINE.QUANTITY) AS PURCHASES,
        CUSTOMER.COUNTRY,
        GENRE.NAME AS GENRE_NAME,
        ROW_NUMBER()
        OVER (PARTITION BY CUSTOMER.COUNTRY
	ORDER BY COUNT(INVOICE_LINE.QUANTITY) DESC) AS ROW_NUM
    FROM INVOICE_LINE
    JOIN INVOICE
    ON INVOICE.INVOICE_ID = INVOICE_LINE.INVOICE_ID
    JOIN CUSTOMER
    ON CUSTOMER.CUSTOMER_ID = INVOICE.CUSTOMER_ID
    JOIN TRACK
    ON TRACK.TRACK_ID = INVOICE_LINE.TRACK_ID
    JOIN GENRE
    ON GENRE.GENRE_ID = TRACK.GENRE_ID
    GROUP BY
		CUSTOMER.COUNTRY,
		GENRE.NAME)

SELECT
	COUNTRY,
	GENRE_NAME,
    PURCHASES
FROM POPULAR_GENRE
WHERE
	ROW_NUM <= 1;
    
    
# =======================================================================================================
# 11. WRITE A QUERY THAT DETERMINES THE CUSTOMER THAT HAS SPENT THE MOST ON MUSIC FOR EACH CONUTRY.
#	  WRITE A QUERY THAT RETURNS THE COUNTRY ALONG WITH THE TOP CUSTOMER AND HOW MUCH THEY SPENT.
#	  FOR THE COUNTRIES WHERE THE TOP AMOUNT SPEND IS SHARED, PROVIDE ALL CUSTOMER WHO SPENT THIS AMOUNT.
# =======================================================================================================
WITH CUSTOMER_WITH_COUNTRY AS
	(SELECT
		CUSTOMER.CUSTOMER_ID,
        FIRST_NAME,
        LAST_NAME,
        BILLING_COUNTRY,
        SUM(TOTAL) AS TOTAL_SPENT,
        ROW_NUMBER()
        OVER(PARTITION BY BILLING_COUNTRY
			ORDER BY
				SUM(TOTAL) DESC) AS ROW_NUM
	FROM INVOICE
    JOIN CUSTOMER
    ON CUSTOMER.CUSTOMER_ID = INVOICE.CUSTOMER_ID
    GROUP BY
		CUSTOMER.CUSTOMER_ID,
        FIRST_NAME,
        LAST_NAME,
        BILLING_COUNTRY
	ORDER BY
		BILLING_COUNTRY,
        TOTAL_SPENT DESC)
SELECT
	CUSTOMER_ID,
    FIRST_NAME,
    LAST_NAME,
    BILLING_COUNTRY,
    TOTAL_SPENT
FROM CUSTOMER_WITH_COUNTRY
WHERE
	ROW_NUM = 1;
    
    
# =====================================
# 12. WHO ARE THE MOST POPULAR ARTISTS?
# =====================================
SELECT
	COUNT(INVOICE_LINE.QUANTITY) AS PURCHASES,
    ARTIST.NAME AS ARTIST_NAME
FROM INVOICE_LINE
JOIN TRACK
ON TRACK.TRACK_ID = INVOICE_LINE.TRACK_ID
JOIN ALBUM
ON ALBUM.ALBUM_ID = TRACK.ALBUM_ID
JOIN ARTIST
ON ARTIST.ARTIST_ID = ALBUM.ARTIST_ID
GROUP BY
	ARTIST.NAME
ORDER BY
	PURCHASES DESC;
    
    
# ===================================
# 13. WHICH IS THE MOST POPULAR SONG?
# ===================================
SELECT
	COUNT(INVOICE_LINE.QUANTITY) AS PURCHASE,
    TRACK.NAME AS SONG_NAME
FROM INVOICE_LINE
JOIN TRACK
ON TRACK.TRACK_ID = INVOICE_LINE.TRACK_ID
GROUP BY
	SONG_NAME
ORDER BY
	PURCHASE DESC;
    
    
# ============================================================
# 14. WHAT ARE THE AVERAGE PRICES OF DIFFERENT TYPES OF MUSIC?
# ============================================================
WITH PURCHASES AS
	(SELECT
		GENRE.NAME AS GENRE,
        SUM(TOTAL) AS TOTAL_SPENT
	FROM INVOICE
    JOIN INVOICE_LINE
    ON INVOICE.INVOICE_ID = INVOICE_LINE.INVOICE_ID
    JOIN TRACK
    ON TRACK.TRACK_ID = INVOICE_LINE.TRACK_ID
    JOIN GENRE
    ON GENRE.GENRE_ID = TRACK.GENRE_ID
    GROUP BY
		GENRE
	ORDER BY
		TOTAL_SPENT)
SELECT
	GENRE,
    CONCAT('$', ROUND(AVG(TOTAL_SPENT))) AS TOTAL_SPENT
FROM PURCHASES
GROUP BY
	GENRE;
    
    
# ============================================================
# 15. WHAT ARE THE MOST POPULAR COUNTRIES FOR MUSIC PURCHASES?
# ============================================================
SELECT
	COUNT(INVOICE_LINE.QUANTITY) AS PURCHASES,
    CUSTOMER.COUNTRY
FROM INVOICE_LINE
JOIN INVOICE
ON INVOICE.INVOICE_ID = INVOICE_LINE.INVOICE_ID
JOIN CUSTOMER
ON CUSTOMER.CUSTOMER_ID = INVOICE.CUSTOMER_ID
GROUP BY
	COUNTRY
ORDER BY
	PURCHASES DESC;